version: '3.7'
services:
  kalilinux:
    hostname: kalilinux.lab
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'csalab/kalilinux-docker:latest'
    volumes:
      - ./root:/root
      - ./sniper:/usr/share/sniper/loot/workspace/
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 0.0.0.0:8080:8080
    working_dir: /root
    environment:
      - SHELL=/bin/bash
      - PASSWORD=kalilinux
    entrypoint: ["/bin/bash", "/startup.sh"]
